/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/monitor_active1v3.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/monitor_active1v3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube071.geometry} material={materials.old_plastic} position={[1.64, 1.523, 0.093]} scale={[0.888, 1, 1]} />
      <mesh geometry={nodes.Display.geometry} material={materials.display_1} position={[1.64, 1.523, 0.093]} scale={[0.888, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/monitor_active1v3.glb')
