/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/monitor_active1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/monitor_active1.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.64, 1.523, 0.093]} scale={[0.888, 1, 1]}>
        <mesh geometry={nodes.Cube078.geometry} material={materials.display_1} />
        <mesh geometry={nodes.Cube078_1.geometry} material={materials.old_plastic} />
      </group>
    </group>
  )
}

useGLTF.preload('/monitor_active1.glb')
